server.port=8080

#langchain4j测试模型
langchain4j.open-ai.chat-model.base-url=http://langchain4j.dev/demo/openai/v1
langchain4j.open-ai.chat-model.api-key=demo
langchain4j.open-ai.chat-model.model-name=gpt-4o-mini

#请求和响应日志
langchain4j.open-ai.chat-model.log-requests=true
langchain4j.open-ai.chat-model.log-responses=true

#启用日志debug级别
logging.level.root=debug

# Redis 配置 (Spring Data Redis)
spring.data.redis.host=localhost
spring.data.redis.port=6379
# 如果有密码，取消注释并填写
spring.data.redis.password=baochuan123
# 如果使用非默认数据库 (0)，取消注释并修改
spring.data.redis.database=1


